Remove dotenv usage from the prod context
We recently merged this change to fix app insights[1] however deploys fail with:

```
Error: Cannot find module 'dotenv/config'
```

Which implies we shouldn’t be importing this anymore.

[1] https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/781